openapi: 3.0.0
info:
  title: Shopbridge API
  version: 1.0.0
servers:
  - url: http://localhost:8000
paths:
  /api/auth/register:
    post:
      summary: Register a new user
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  example: johndoe
                password:
                  type: string
                  example: mysecretpassword
      responses:
        '201':
          description: User registered successfully
        '400':
          description: Invalid request body
  /api/auth/login:
    post:
      summary: Login as an existing user
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  example: johndoe
                password:
                  type: string
                  example: mysecretpassword
      responses:
        '200':
          description: User authenticated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  access_token:
                    type: string
                    example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
                  refresh_token:
                    type: string
                    example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
        '401':
          description: Invalid username or password
  /api/auth/logout:
    delete:
      summary: Logout the current user
      responses:
        '204':
          description: User logged out successfully
        '401':
          description: Unauthorized
  /api/auth/refresh:
    post:
      summary: Refresh the access token of the current user
      responses:
        '200':
          description: Token refreshed successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  access_token:
                    type: string
                    example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
  /api/items:
    get:
      summary: Get a list of all items
      responses:
        '200':
          description: Items retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      example: 1
                    name:
                      type: string
                      example: Product A
                    description:
                      type: string
                      example: A description of Product A
                    price:
                      type: number
                      example: 10.99
                    quantity:
                      type: integer
                      example: 50
    post:
      summary: Create a new item
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: Product A
                description:
                  type: string
                  example: A description of Product A
                price:
                  type: number
                  example: 10.99
                quantity:
                  type: integer
                  example: 50
      responses:
        '201':
          description: Item created successfully
        '400':
          description: Invalid request body
  /api/items/{id}:
    parameters:
      - name: id
        in: path
        required: true
        description: ID of the item to retrieve or update
        schema:
          type: integer
    get:
      summary: Get a specific item by ID
      responses:
        '200':
          description: Item retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    example: 1
                  name:
                    type: string
                    example: Product A
                  description:
                    type: string
                    example: A description of Product A
                  price:
                    type: number
                    example: 10.99
                  quantity:
                    type: integer
                    example: 50
        '404':
          description: Item not found
    put:
      summary: Update a specific item by ID
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: Product A (updated)
                description:
                  type: string
                  example: An updated description of Product A
                price:
                  type: number
                  example: 12.99
                quantity:
                  type: integer
                  example: 25
      responses:
        '200':
          description: Item updated successfully
        '400':
          description: Invalid request body or parameters
        '404':
          description: Item not found
    delete:
      summary: Delete an existing item
      responses:
        '204':
          description: Item deleted successfully
        '404':
          description: Item not found
  /api/items/bulkcreate:
    post:
      summary: Create multiple items at once
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                items:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                        example: Product A
                      description:
                        type: string
                        example: A description of Product A
                      price:
                        type: number
                        example: 10.99
                      quantity:
                        type: integer
                        example: 50
      responses:
        '201':
          description: Items created successfully
        '400':
          description: Invalid request body
